#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run format
npm run lint
npm run test:coverage
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "Pre-commit failed: Formatting, linting, or test coverage errors found."
  exit 1
fi

# Re-stage all changes after fixing
git add .

# Optionally, run lint again to ensure no errors remain
# npm run lint
